apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-12-01T08:03:42Z"
  labels:
    app: pages
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-12-01T08:03:42Z"
  name: pages
  namespace: angel
  resourceVersion: "213997"
  selfLink: /api/v1/namespaces/angel/services/pages
  uid: a5f2bc32-7f57-4124-bc11-d0f03ef2ce74
spec:
  clusterIP: 10.100.159.247
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pages
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
